name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Maven Install
      run: mvn install
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag soj:$(date +%s) --tag soj:latest
    - name: Run
      run: docker run soj:latest
